const medicos = [
  {
    id: 1,
    nome: 'Dr. José Amaral',
    iniciais: 'JA',
    crm: 'CRM 12.345/SP',
    especialidade: 'Dermatologia',
    clinica: 'Alphaville',
    endereco: 'Alameda Araguaia, 871 – Alphaville/SP',
    avatarGradient: null,
    proximaData: 'Dom, 26/04',
    proximaDataCor: 'var(--cp-blue)',
    cobertura: 'total',
    planoAceito: true,
    descontoPrata: true,
    distancia: null,
    preco: null,
  },
  {
    id: 2,
    nome: 'Dra. Cintia Costa',
    iniciais: 'CC',
    crm: 'CRM 8.711/SP',
    especialidade: 'Odontologia',
    clinica: 'Nações Unidas',
    endereco: 'Av. das Nações Unidas, 12.901 – SP',
    avatarGradient: 'linear-gradient(135deg,#7986CB,#00BCD4)',
    proximaData: 'Hoje, 17:35',
    proximaDataCor: 'var(--cp-green)',
    cobertura: null,
    planoAceito: false,
    descontoPrata: true,
    distancia: null,
    preco: 'A partir de R$ 150,00',
  },
  {
    id: 3,
    nome: 'Dr. Flávio Santos',
    iniciais: 'FS',
    crm: 'CRM 5.632/SP',
    especialidade: 'Clínica Geral',
    clinica: 'Consolação',
    endereco: 'Rua Luís Coelho, 223 – Consolação',
    avatarGradient: 'linear-gradient(135deg,#43A047,#1B5E20)',
    proximaData: 'Sáb, 03/05',
    proximaDataCor: 'var(--cp-blue)',
    cobertura: 'total',
    planoAceito: true,
    descontoPrata: false,
    distancia: '10 km',
    preco: null,
  },
  {
    id: 4,
    nome: 'Dra. Mariana Lopes',
    iniciais: 'ML',
    crm: 'CRM 14.820/SP',
    especialidade: 'Endocrinologia',
    clinica: 'Jardins',
    endereco: 'Rua Oscar Freire, 440 – Jardins/SP',
    avatarGradient: 'linear-gradient(135deg,#F06292,#CE93D8)',
    proximaData: 'Seg, 28/04',
    proximaDataCor: 'var(--cp-blue)',
    cobertura: 'total',
    planoAceito: true,
    descontoPrata: true,
    distancia: '7 km',
    preco: null,
  },
  {
    id: 5,
    nome: 'Dr. Ricardo Motta',
    iniciais: 'RM',
    crm: 'CRM 9.301/SP',
    especialidade: 'Cardiologia',
    clinica: 'Paulista',
    endereco: 'Av. Paulista, 1.000 – Bela Vista/SP',
    avatarGradient: 'linear-gradient(135deg,#E53935,#B71C1C)',
    proximaData: 'Ter, 29/04',
    proximaDataCor: 'var(--cp-blue)',
    cobertura: 'total',
    planoAceito: true,
    descontoPrata: false,
    distancia: '5 km',
    preco: null,
  },
  {
    id: 6,
    nome: 'Dra. Patrícia Nunes',
    iniciais: 'PN',
    crm: 'CRM 7.145/SP',
    especialidade: 'Saúde Ocupacional',
    clinica: 'Vila Olímpia',
    endereco: 'Rua Funchal, 263 – Vila Olímpia/SP',
    avatarGradient: 'linear-gradient(135deg,#0288D1,#01579B)',
    proximaData: 'Qui, 01/05',
    proximaDataCor: 'var(--cp-blue)',
    cobertura: null,
    planoAceito: true,
    descontoPrata: true,
    distancia: '12 km',
    preco: 'A partir de R$ 200,00',
  },

  // Dermatologia
  {
    id: 7,
    nome: 'Dra. Ana Beatriz Lima',
    iniciais: 'AB',
    crm: 'CRM 18.302/SP',
    especialidade: 'Dermatologia',
    clinica: 'Moema',
    endereco: 'Av. Ibirapuera, 2.100 – Moema/SP',
    avatarGradient: 'linear-gradient(135deg,#F48FB1,#E91E63)',
    proximaData: 'Hoje, 14:00',
    proximaDataCor: 'var(--cp-green)',
    cobertura: null,
    planoAceito: false,
    descontoPrata: false,
    distancia: '8 km',
    preco: 'A partir de R$ 180,00',
  },
  {
    id: 8,
    nome: 'Dr. Carlos Mendes',
    iniciais: 'CM',
    crm: 'CRM 11.540/SP',
    especialidade: 'Dermatologia',
    clinica: 'Pinheiros',
    endereco: 'Rua dos Pinheiros, 515 – Pinheiros/SP',
    avatarGradient: 'linear-gradient(135deg,#80CBC4,#00695C)',
    proximaData: 'Qua, 07/05',
    proximaDataCor: 'var(--cp-blue)',
    cobertura: 'total',
    planoAceito: true,
    descontoPrata: false,
    distancia: '4 km',
    preco: null,
  },

  // Odontologia
  {
    id: 9,
    nome: 'Dr. Bruno Takeda',
    iniciais: 'BT',
    crm: 'CRO 6.823/SP',
    especialidade: 'Odontologia',
    clinica: 'Higienópolis',
    endereco: 'Av. Angélica, 1.900 – Higienópolis/SP',
    avatarGradient: 'linear-gradient(135deg,#FFB74D,#E65100)',
    proximaData: 'Hoje, 10:30',
    proximaDataCor: 'var(--cp-green)',
    cobertura: 'total',
    planoAceito: true,
    descontoPrata: false,
    distancia: '6 km',
    preco: null,
  },
  {
    id: 10,
    nome: 'Dra. Fernanda Rocha',
    iniciais: 'FR',
    crm: 'CRO 9.217/SP',
    especialidade: 'Odontologia',
    clinica: 'Tatuapé',
    endereco: 'Rua Tuiuti, 740 – Tatuapé/SP',
    avatarGradient: 'linear-gradient(135deg,#A5D6A7,#1B5E20)',
    proximaData: 'Sex, 09/05',
    proximaDataCor: 'var(--cp-blue)',
    cobertura: 'total',
    planoAceito: true,
    descontoPrata: false,
    distancia: '14 km',
    preco: null,
  },

  // Clínica Geral
  {
    id: 11,
    nome: 'Dr. Eduardo Pires',
    iniciais: 'EP',
    crm: 'CRM 21.087/SP',
    especialidade: 'Clínica Geral',
    clinica: 'Santa Cecília',
    endereco: 'Rua Coronel Melo de Oliveira, 321 – Santa Cecília/SP',
    avatarGradient: 'linear-gradient(135deg,#CE93D8,#6A1B9A)',
    proximaData: 'Hoje, 09:00',
    proximaDataCor: 'var(--cp-green)',
    cobertura: null,
    planoAceito: false,
    descontoPrata: true,
    distancia: '3 km',
    preco: 'A partir de R$ 120,00',
  },
  {
    id: 12,
    nome: 'Dra. Larissa Teixeira',
    iniciais: 'LT',
    crm: 'CRM 16.654/SP',
    especialidade: 'Clínica Geral',
    clinica: 'Lapa',
    endereco: 'Rua Guaicurus, 890 – Lapa/SP',
    avatarGradient: 'linear-gradient(135deg,#80DEEA,#006064)',
    proximaData: 'Ter, 06/05',
    proximaDataCor: 'var(--cp-blue)',
    cobertura: 'total',
    planoAceito: true,
    descontoPrata: true,
    distancia: '9 km',
    preco: null,
  },

  // Endocrinologia
  {
    id: 13,
    nome: 'Dr. Henrique Farias',
    iniciais: 'HF',
    crm: 'CRM 13.490/SP',
    especialidade: 'Endocrinologia',
    clinica: 'Itaim Bibi',
    endereco: 'Rua Iguatemi, 192 – Itaim Bibi/SP',
    avatarGradient: 'linear-gradient(135deg,#FFCC80,#E65100)',
    proximaData: 'Hoje, 16:00',
    proximaDataCor: 'var(--cp-green)',
    cobertura: null,
    planoAceito: false,
    descontoPrata: false,
    distancia: '11 km',
    preco: 'A partir de R$ 250,00',
  },
  {
    id: 14,
    nome: 'Dra. Sophia Andrade',
    iniciais: 'SA',
    crm: 'CRM 19.776/SP',
    especialidade: 'Endocrinologia',
    clinica: 'Brooklin',
    endereco: 'Av. Santo Amaro, 4.700 – Brooklin/SP',
    avatarGradient: 'linear-gradient(135deg,#B39DDB,#4527A0)',
    proximaData: 'Qui, 08/05',
    proximaDataCor: 'var(--cp-blue)',
    cobertura: 'total',
    planoAceito: true,
    descontoPrata: false,
    distancia: '15 km',
    preco: null,
  },

  // Cardiologia
  {
    id: 15,
    nome: 'Dra. Renata Cardoso',
    iniciais: 'RC',
    crm: 'CRM 10.238/SP',
    especialidade: 'Cardiologia',
    clinica: 'Liberdade',
    endereco: 'Rua Galvão Bueno, 540 – Liberdade/SP',
    avatarGradient: 'linear-gradient(135deg,#EF9A9A,#B71C1C)',
    proximaData: 'Hoje, 11:15',
    proximaDataCor: 'var(--cp-green)',
    cobertura: null,
    planoAceito: false,
    descontoPrata: true,
    distancia: '7 km',
    preco: 'A partir de R$ 300,00',
  },
  {
    id: 16,
    nome: 'Dr. Gustavo Alves',
    iniciais: 'GA',
    crm: 'CRM 15.903/SP',
    especialidade: 'Cardiologia',
    clinica: 'Morumbi',
    endereco: 'Av. Giovanni Gronchi, 5.900 – Morumbi/SP',
    avatarGradient: 'linear-gradient(135deg,#F48FB1,#880E4F)',
    proximaData: 'Seg, 05/05',
    proximaDataCor: 'var(--cp-blue)',
    cobertura: 'total',
    planoAceito: true,
    descontoPrata: true,
    distancia: '18 km',
    preco: null,
  },

  // Saúde Ocupacional
  {
    id: 17,
    nome: 'Dr. Thiago Barbosa',
    iniciais: 'TB',
    crm: 'CRM 22.411/SP',
    especialidade: 'Saúde Ocupacional',
    clinica: 'Santo André',
    endereco: 'Av. Industrial, 600 – Santo André/SP',
    avatarGradient: 'linear-gradient(135deg,#90CAF9,#0D47A1)',
    proximaData: 'Hoje, 13:45',
    proximaDataCor: 'var(--cp-green)',
    cobertura: null,
    planoAceito: false,
    descontoPrata: false,
    distancia: '22 km',
    preco: 'A partir de R$ 160,00',
  },
  {
    id: 18,
    nome: 'Dra. Camila Reis',
    iniciais: 'CR',
    crm: 'CRM 8.567/SP',
    especialidade: 'Saúde Ocupacional',
    clinica: 'ABC Paulista',
    endereco: 'Rua Marechal Deodoro, 120 – São Bernardo/SP',
    avatarGradient: 'linear-gradient(135deg,#80CBC4,#004D40)',
    proximaData: 'Qua, 07/05',
    proximaDataCor: 'var(--cp-blue)',
    cobertura: null,
    planoAceito: false,
    descontoPrata: true,
    distancia: '25 km',
    preco: 'A partir de R$ 140,00',
  },
];