const medicos = [
  {
    id: 1,
    nome: 'Dr. José Amaral',
    iniciais: 'JA',
    crm: 'CRM 12.345/SP',
    especialidade: 'Dermatologia',
    clinica: 'Alphaville',
    endereco: 'Alameda Araguaia, 871 – Alphaville/SP',
    avatarGradient: null,
    proximaData: 'Dom, 26/04',
    proximaDataCor: 'var(--cp-blue)',
    cobertura: 'total',
    planoAceito: true,
    descontoPrata: true,
    distancia: null,
    preco: null,
  },
  {
    id: 2,
    nome: 'Dra. Cintia Costa',
    iniciais: 'CC',
    crm: 'CRM 8.711/SP',
    especialidade: 'Odontologia',
    clinica: 'Nações Unidas',
    endereco: 'Av. das Nações Unidas, 12.901 – SP',
    avatarGradient: 'linear-gradient(135deg,#7986CB,#00BCD4)',
    proximaData: 'Hoje, 17:35',
    proximaDataCor: 'var(--cp-green)',
    cobertura: null,
    planoAceito: false,
    descontoPrata: true,
    distancia: null,
    preco: 'A partir de R$ 150,00',
  },
  {
    id: 3,
    nome: 'Dr. Flávio Santos',
    iniciais: 'FS',
    crm: 'CRM 5.632/SP',
    especialidade: 'Clínica Geral',
    clinica: 'Consolação',
    endereco: 'Rua Luís Coelho, 223 – Consolação',
    avatarGradient: 'linear-gradient(135deg,#43A047,#1B5E20)',
    proximaData: 'Sáb, 03/05',
    proximaDataCor: 'var(--cp-blue)',
    cobertura: 'total',
    planoAceito: true,
    descontoPrata: false,
    distancia: '10 km',
    preco: null,
  },
  {
    id: 4,
    nome: 'Dra. Mariana Lopes',
    iniciais: 'ML',
    crm: 'CRM 14.820/SP',
    especialidade: 'Endocrinologia',
    clinica: 'Jardins',
    endereco: 'Rua Oscar Freire, 440 – Jardins/SP',
    avatarGradient: 'linear-gradient(135deg,#F06292,#CE93D8)',
    proximaData: 'Seg, 28/04',
    proximaDataCor: 'var(--cp-blue)',
    cobertura: 'total',
    planoAceito: true,
    descontoPrata: true,
    distancia: '7 km',
    preco: null,
  },
  {
    id: 5,
    nome: 'Dr. Ricardo Motta',
    iniciais: 'RM',
    crm: 'CRM 9.301/SP',
    especialidade: 'Cardiologia',
    clinica: 'Paulista',
    endereco: 'Av. Paulista, 1.000 – Bela Vista/SP',
    avatarGradient: 'linear-gradient(135deg,#E53935,#B71C1C)',
    proximaData: 'Ter, 29/04',
    proximaDataCor: 'var(--cp-blue)',
    cobertura: 'total',
    planoAceito: true,
    descontoPrata: false,
    distancia: '5 km',
    preco: null,
  },
  {
    id: 6,
    nome: 'Dra. Patrícia Nunes',
    iniciais: 'PN',
    crm: 'CRM 7.145/SP',
    especialidade: 'Saúde Ocupacional',
    clinica: 'Vila Olímpia',
    endereco: 'Rua Funchal, 263 – Vila Olímpia/SP',
    avatarGradient: 'linear-gradient(135deg,#0288D1,#01579B)',
    proximaData: 'Qui, 01/05',
    proximaDataCor: 'var(--cp-blue)',
    cobertura: null,
    planoAceito: true,
    descontoPrata: true,
    distancia: '12 km',
    preco: 'A partir de R$ 200,00',
  },
];